name: 'changelog'
description: 'tag the repo and update the CHANGELOG.md with the latest conventional commits'

inputs:
  version_tag:
    description: 'version tag to use'
    required: false
    default: "next_tag"
    type: string
  slack_channel:
    description: 'slack channel to alert'
    required: false
    default: "keyevent-dev"
    type: string

runs:
  using: "composite"
  steps:
    - name: adjust the path to include the actions path so scripts in the action can be run
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - name: tag repo create changelog and create release
      run: changelog.sh -t ${{ inputs.version_tag }} --release --slack_channel keyevent-dev
      shell: bash
      # handle when empty input is provided
      env:
        GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        SLACKTEE_TOKEN: ${{ secrets.SLACKTEE_TOKEN }}

